#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap "us(intl)" &
xsetroot -cursor_name left_ptr &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
~/.fehbg
dunst &
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width            2
bspc config window_gap              10
bspc config top_padding             38

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#ECEFF4"
bspc config focused_border_color    "#81A1C1"

# Chat
bspc rule -a Slack desktop='^6' follow=on
bspc rule -a discord desktop='^6' follow=on

# Creatives
bspc rule -a Joplin desktop='^4' follow=on
bspc rule -a Gimp-2.10 desktop='^4' follow=on
bspc rule -a Inkscape desktop='^4' follow=on
bspc rule -a Blender desktop='^4' follow=on
bspc rule -a Godot desktop='^4' follow=on

# Settings
bspc rule -a Lxappearance desktop='^5' follow=on
bspc rule -a Pavucontrol desktop='^5' follow=on
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a Nitrogen desktop='^5' follow=on

# Browser
bspc rule -a firefox desktop='^3' follow=on

# Code
bspc rule -a code-oss desktop='^2' follow=on

# Terminal
bspc rule -a kitty desktop='^1' follow=on
